vyigity.Blog/Controllers/ArticleController.cs
using ProjectBase.Database;
using ProjectBase.Utility;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vyigity.Blog.Models;

namespace vyigity.Blog.Controllers
{
    public class ArticleController : Controller
    {
        // GET: Article
        public ActionResult Index()
        {
            ProcessView();

            //Article arc = GetData();

            return View(new Article());
        }

        public ActionResult ArticleUpdate(int id)
        {
            ProcessView();

            List<Category> allcats = GetCategory();
            List<Category> loadedcats = GetLoadedCategory(id);

            ViewData["unloadedCategory"] = allcats.Where(r => !loadedcats.Any(z => z.ID == r.ID)).ToList();
            ViewData["loadedCats"] = loadedcats;

            Article arc = GetData(id);

            return View("ArticleUpdate", arc);
        }

        [ValidateInput(false)]
        public ActionResult UpdateArticle(int ARTICLE_ID, string TITLE, string CONTENT, int[] CATEGORIES)
        {
            try
            {
                IDatabase2 db = DatabaseFactory.GetDbObject(DbSettings.TransactionMode);
                IQueryGenerator gen = QueryGeneratorFactory.GetDbObject();

                gen.TableName = "article";

                gen.AddDataParameter("TITLE", TITLE);
                gen.AddDataParameter("TEXT", CONTENT);
                gen.AddDataParameter("UPDATE_DATE", DateTime.Now);
                gen.AddDataParameter("AUTHOR", "vyigity");

                gen.FilterText = " where ID=:p1";

                gen.AddFilterParameter("p1", ARTICLE_ID);

                db.ExecuteQuery(gen.GetUpdateCommand());

                db.ExecuteQuery("delete from article_category where article_id = " + ARTICLE_ID);

                if (CATEGORIES != null && CATEGORIES.Length > 0)
                {
                    foreach (int i in CATEGORIES)
                    {
                        IQueryGenerator gen3 = QueryGeneratorFactory.GetDbObject();
                        gen3.TableName = "article_category";

                        gen3.AddDataParameter("ARTICLE_ID", ARTICLE_ID);
                        gen3.AddDataParameter("CATEGORY_ID", i);

                        db.ExecuteQuery(gen3.GetInsertCommand());
                    }
                }

                db.Commit();

                return RedirectToAction("ManageArticle");
            }
            catch
            {
                return RedirectToAction("ArticleUpdate");
            }
        }

        public ActionResult ManageArticle()
        {
            ProcessView();

            List<Article> arcs = GetAllData();

            return View(arcs);
        }

        private List<Article> GetAllData()
        {
            IDatabase2 db = DatabaseFactory.GetDbObject();
            IQueryGenerator gen = QueryGeneratorFactory.GetDbObject();

            gen.SelectText = "select * from article order by INSERT_DATE desc";

            List<Article> sonuc = db.GetObjectList<Article>(gen.GetSelectCommandBasic());

            return sonuc;
        }

        private Article GetData(int id)
        {
            IDatabase2 db = DatabaseFactory.GetDbObject();
            IQueryGenerator gen = QueryGeneratorFactory.GetDbObject();

            gen.SelectText = "select * from article where ";
            gen.FilterText = "id=:p1";

            gen.AddFilterParameter("p1", id);

            Article sonuc = db.GetObject<Article>(gen.GetSelectCommandBasic());

            return sonuc;
        }

        private void ProcessView()
        {
            ViewData["Category"] = GetCategory();
        }

        private static List<Category> GetCategory()
        {
            IDatabase2 db = DatabaseFactory.GetDbObject();
            List<Category> aList = db.GetObjectList<Category>(
                "select c.*, (select count(*) from article_category a where a.category_id = c.id) ARTICLE_COUNT from category c order by LABEL_TEXT");
            return aList;
        }

        private static List<Category> GetLoadedCategory(int id)
        {
            IDatabase2 db = DatabaseFactory.GetDbObject();
            IQueryGenerator gen = QueryGeneratorFactory.GetDbObject();
            gen.SelectText = "select c.* from category c, article_category ac where ";
            gen.FilterText = "c.id = ac.category_id and ac.article_id = :p1 ";
            gen.SelectTail = "order by c.LABEL_TEXT";

            gen.AddFilterParameter("p1", id);

            List<Category> aList = db.GetObjectList<Category>(gen.GetSelectCommandBasic());
            return aList;
        }

        [ValidateInput(false)]
        public ActionResult AddArticle(string TITLE, string CONTENT, int[] CATEGORIES)
        {
            try
            {
                string nGuid = Guid.NewGuid().ToString("N");

                IDatabase2 db = DatabaseFactory.GetDbObject(DbSettings.TransactionMode);
                IQueryGenerator gen = QueryGeneratorFactory.GetDbObject();

                gen.TableName = "article";

                gen.AddDataParameter("TITLE", TITLE);
                gen.AddDataParameter("TEXT", CONTENT);
                gen.AddDataParameter("INSERT_DATE", DateTime.Now);
                gen.AddDataParameter("AUTHOR", "vyigity");
                gen.AddDataParameter("ID_GUID", nGuid);

                db.ExecuteQuery(gen.GetInsertCommand());

                IQueryGenerator gen2 = QueryGeneratorFactory.GetDbObject();
                gen2.SelectText = "select ID from article where ";
                gen2.FilterText = "ID_GUID = :p1";
                gen2.AddFilterParameter("p1", nGuid);

                if (CATEGORIES != null && CATEGORIES.Length > 0)
                {
                    int id = Util.GetProperty<int>(db.GetSingleValue(gen2.GetSelectCommandBasic()));

                    foreach (int i in CATEGORIES)
                    {
                        IQueryGenerator gen3 = QueryGeneratorFactory.GetDbObject();
                        gen3.TableName = "article_category";

                        gen3.AddDataParameter("ARTICLE_ID", id);
                        gen3.AddDataParameter("CATEGORY_ID", i);

                        db.ExecuteQuery(gen3.GetInsertCommand());
                    }
                }

                db.Commit();

                ProcessView();

                return RedirectToAction("ManageArticle");
            }
            catch
            {
                return RedirectToAction("Index");
            }
        }

        public ActionResult ProcessArticle(int ARTICLE_ID, int ISLEM)
        {
            try
            {
                IDatabase2 db = DatabaseFactory.GetDbObject(DbSettings.TransactionMode);
                IQueryGenerator gen = QueryGeneratorFactory.GetDbObject();

                gen.TableName = "article";

                gen.AddDataParameter("ACTIVE", ISLEM);

                gen.FilterText = "where ID=:p1";

                gen.AddFilterParameter("p1", ARTICLE_ID);

                db.ExecuteQuery(gen.GetUpdateCommand());

                db.Commit();

                return RedirectToAction("ManageArticle");
            }
            catch
            {
                return RedirectToAction("ManageArticle");
            }
        }
    }
}

vyigity.Blog/Controllers/CommentController.cs
using ProjectBase.Database;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using vyigity.Blog.Models;

namespace vyigity.Blog.Controllers
{
    public class CommentController : Controller
    {
        // GET: Comment
        public ActionResult Index()
        {
            List<Comment> cList = ProcessView();

            return View(cList);
        }

        private List<Comment> ProcessView()
        {
            List<Comment> cList = GetData();
            ViewData["Category"] = GetCategory();
            ControlComments(cList);
            return cList;
        }

        private static void ControlComments(List<Comment> cList)
        {
            IDatabase2 db = DatabaseFactory.GetDbObject();
            List<BadWord> bwList = db.GetObjectList<BadWord>("select * from blog.bad_word");

            foreach (var item in cList)
            {
                item.CAUTION = false;
                
                foreach (var bw in bwList)
                {
                    List<string> strList = item.ARTICLE_TITLE.Split(' ').ToList();
                    strList.AddRange(item.COMMENT_TEXT.Split(' ').ToList());

                    foreach (string s in strList)
                    {
                        if (s.StartsWith(bw.WORD, StringComparison.CurrentCultureIgnoreCase))

                            item.CAUTION = true;
                    }
                }    
            }
        }

        private static List<Category> GetCategory()
        {
            IDatabase2 db = DatabaseFactory.GetDbObject();
            List<Category> aList = db.GetObjectList<Category>(
                "select c.*, (select count(*) from article a, article_category ac where a.id = ac.article_id and a.ACTIVE=1 and ac.category_id = c.id) ARTICLE_COUNT from category c order by LABEL_TEXT");
            return aList;
        }

        private static List<Comment> GetData()
        {
            IDatabase2 db = DatabaseFactory.GetDbObject();
            IQueryGenerator gen = QueryGeneratorFactory.GetDbObject();

            gen.SelectText = @"select c.*, a.TITLE ARTICLE_TITLE from blog.comment c, blog.article a 

                                where

                                c.ARTICLE_ID = a.ID and

                                c.APPROVED = 0 order by INSERT_DATE desc";

            return db.GetObjectList<Comment>(gen.GetSelectCommandBasic());
        }

        [HttpPost]
        public ActionResult AddComment(Comment param)
        {
            IDatabase2 db = DatabaseFactory.GetDbObject();
            IQueryGenerator gen = QueryGeneratorFactory.GetDbObject();

            gen.TableName = "comment";

            gen.AddDataParameter("ID", Guid.NewGuid().ToString("N"));
            gen.AddDataParameter("ARTICLE_ID", param.ARTICLE_ID);
            gen.AddDataParameter("COMMENT_TEXT", param.COMMENT_TEXT);
            gen.AddDataParameter("USER_NAME", param.USER_NAME);
            gen.AddDataParameter("INSERT_DATE", DateTime.Now);

            db.ExecuteQuery(gen.GetInsertCommand());

            return Json(new { });
        }

        public ActionResult Process(string ID, int ISLEM)
        {
            IDatabase2 db = DatabaseFactory.GetDbObject();

            IQueryGenerator gen = QueryGeneratorFactory.GetDbObject();
            gen.TableName = "comment";

            if (ISLEM == 1)
            {
                gen.AddDataParameter("APPROVED", 1);
            }
            else
            {
                gen.AddDataParameter("APPROVED", 2);
            }

            gen.FilterText = " WHERE ID=:p1";

            gen.AddFilterParameter("p1", ID);

            db.ExecuteQuery(gen.GetUpdateCommand());

            List<Comment> cList = ProcessView();

            return View("Index", cList);
        }
    }
}

vyigity.Blog/Views/Shared/_Layout.cshtml
@using vyigity.Blog.Code;
@using vyigity.Blog.Models;

@{
    BlogAuthentication aut = new BlogAuthentication();
}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Veli Yigit YOLCU</title>

    @Scripts.Render("~/bundles/jquery")

    @Scripts.Render("~/bundles/jqueryval")

    @Scripts.Render("~/bundles/bootstrap")

    @RenderSection("scripts", required: false)


    @Styles.Render("~/Content/css")
    @*@Scripts.Render("~/bundles/modernizr")*@

    <link href="~/Content/blog-home.css" rel="stylesheet" />

    <script>

        function submitLogin() {

            $("#loginForm").submit();
        }

        function submitLogout() {

            $("#logoutForm").submit();
        }

        function search() {

            $("#searchForm").submit();

        }


    </script>

</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
            <a class="navbar-brand" href="#">Veli Yigit YOLCU</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="@Url.Action("Index","Home")">
                            Anasayfa
                            <span class="sr-only">(current)</span>
                        </a>
                    </li>

                    @*<li class="nav-item">
                        <a class="nav-link" href="#">İletişim</a>
                    </li>*@

                    @if (!aut.IsAuthenticated())
                    {

                        <li class="nav-item">
                            <a class="nav-link" href="#" data-toggle="modal" data-target="#loginModal">Giriş</a>
                        </li>

                    }
                    else
                    {

                        <li class="nav-item">
                            <a style="color:crimson" class="nav-link" href="@Url.Action("Index","Article")">Yazı Yaz</a>
                        </li>

                        <li class="nav-item">
                            <a style="color:crimson" class="nav-link" href="@Url.Action("ManageArticle","Article")">Yazıları Yönet</a>
                        </li>

                        <li class="nav-item">
                            <a style="color:crimson" class="nav-link" href="@Url.Action("Index","Comment")">Yorumlar</a>
                        </li>

                        <li class="nav-item">
                            <a style="color:crimson" class="nav-link" href="@Url.Action("Index","Category")">Etiketler</a>
                        </li>

                        <li class="nav-item">
                            <a style="color:crimson" class="nav-link" href="#" onclick="submitLogout()">Çıkış</a>
                        </li>

                    }
                </ul>
            </div>
        </div>
    </nav>

    @*<div class="container body-content">

            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>*@

    <!-- Page Content -->



    <div class="container">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8">
                <h1 class="my-4">
                    Veli Yigit YOLCU
                    <small>Senior Software Engineer</small>
                </h1>
                <!-- Blog Post -->

                @RenderBody()

                <!-- Pagination -->
                @*<ul class="pagination justify-content-center mb-4">
                    <li class="page-item">
                        <a class="page-link" href="#">&larr; Geri</a>
                    </li>
                    <li class="page-item disabled">
                        <a class="page-link" href="#">İleri &rarr;</a>
                    </li>
                </ul>*@
            </div>
            <!-- Sidebar Widgets Column -->
            <div class="col-md-4">
                <!-- Search Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Arama</h5>
                    <div class="card-body">
                        <div class="input-group">

                            <form id="searchForm" action="~/Home/Search" method="post">
                                <input id="searchText" name="searchText" type="text" class="form-control" placeholder="Aranacak içerik giriniz...">
                            </form>
                            <span class="input-group-btn">
                                <button class="btn btn-secondary" onclick="search()" type="button">ARA</button>
                            </span>
                        </div>
                    </div>
                </div>
                <!-- Categories Widget -->
                <div class="card my-4">
                    <h5 class="card-header">Etiketler</h5>
                    @{
                        var categories = ViewData["Category"] as List<Category>;
                        int part1 = categories.Count / 2;
                    }
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-6">
                                <ul class="list-unstyled mb-0">
                                    @for (int i = 0; i < part1; i++)
                                    {
                                        <li>
                                            <a href="@Url.Action("Category","Home",new { id= categories[i].ID })">@(categories[i].LABEL_TEXT + " (" + categories[i].ARTICLE_COUNT + ")")</a>
                                        </li>
                                    }
                                </ul>
                            </div>
                            <div class="col-lg-6">
                                <ul class="list-unstyled mb-0">
                                    @for (int i = part1; i < categories.Count; i++)
                                    {
                                        <li>
                                            <a href="@Url.Action("Category","Home",new { id= categories[i].ID })">@(categories[i].LABEL_TEXT + " (" + categories[i].ARTICLE_COUNT + ")")</a>
                                        </li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Side Widget -->
                @*<div class="card my-4">
                        <h5 class="card-header">Side Widget</h5>
                        <div class="card-body">
                            You can put anything you want inside of these side widgets. They are easy to use, and feature the new Bootstrap 4 card containers!
                        </div>
                    </div>*@
            </div>
        </div>
        <!-- /.row -->
    </div>

    <!-- Login Modal -->
    <div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Kullanıcı Girişi</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="loginForm" action="~/Home/Login" method="post">
                        <div class="form-group">
                            <label for="UserName" class="col-form-label">Kullanıcı Adı:</label>
                            <input type="text" class="form-control" id="UserName" name="UserName">
                        </div>
                        <div class="form-group">
                            <label for="Password" class="col-form-label">Şifre:</label>
                            <input type="password" class="form-control" id="Password" name="Password">
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">KAPAT</button>
                    <button type="button" class="btn btn-primary" onclick="submitLogin()">GİRİŞ</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Comment Modal -->
    @*<div class="modal fade" id="commentModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Yorum Girişi</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="commentForm" action="~/Home/Login" method="post">
                        <div class="form-group">
                            <label for="CommentUserName" class="col-form-label">Kullanıcı Adı:</label>
                            <input type="text" class="form-control" id="CommentUserName" name="CommentUserName">
                        </div>
                        <div class="form-group">
                            <label for="Password" class="col-form-label">Yorum:</label>
                            <textarea class="form-control" id="UserComment" name="UserComment"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">KAPAT</button>
                    <button type="button" class="btn btn-primary" onclick="submitLogin()">GİRİŞ</button>
                </div>
            </div>
        </div>
    </div>*@

    <form id="logoutForm" action="~/Home/Logout"></form>


    



</body>
</html>